# docker-compose up --force-recreate -d
version: '3.2'
services:
  git:
    image: wxnacy/git:latest
    container_name: git
    restart: always
    volumes:
      - ~/Projects:/root/Projects
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_EMAIL=${GIT_EMAIL}
      - GIT_PASSWORD=${GIT_PASSWORD}

